CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (225) NOT NULL
);

CREATE TABLE states (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    state VARCHAR (255) UNIQUE NOT NULL,
    city VARCHAR (255) UNIQUE NOT NULL,
    best-cheap-beer-spot VARCHAR (255) UNIQUE NOT NULL,
    bcbs-link VARCHAR (255) UNIQUE NOT NULL,
    best-dog-friendly-spot VARCHAR (255) UNIQUE NOT NULL,
    bdfs-link VARCHAR (255) UNIQUE NOT NULL,
    best-outdoorsy-spot VARCHAR (255) UNIQUE NOT NULL,
    bos-link VARCHAR (255) UNIQUE NOT NULL,
    best-local-fast-food-spot VARCHAR (255) UNIQUE NOT NULL,
    blffs-link VARCHAR (255) UNIQUE NOT NULL
);

--  add user functionality to suggestions (not just anonymous)



