module.exports = {
  states: [
      {
          id: '1',
          state: 'Alabama',
          city: 'Huntsville',
          "best-cheap-beer-spot": 'Voodoo Lounge',
          "bcbs-link": 'https: //www.voodooloungehsv.com',
          "best-dog-friendly-spot": 'City of Huntsville Dogspot',
          "bdfs-link": 'https: //www.huntsvilleal.gov/environment/animal-services/pet-services/dog-parks/',
          "best-outdoorsy-spot": 'Aldridge Creek Greenway',
          "bos-link": 'https: //ourvalleyevents.com/8-favorite-places-for-free-fun-in-the-huntsville-outdoors/',
          "best-local-fast-food-spot": 'Shaggys Burgers and Tacos',
          "blffs-link": 'https: //www.shaggysburgersandtacos.com'
      },
      {
          id: '2',
          state: 'Alabama',
          city: 'Gulf Shores',
          "best-cheap-beer-spot": 'Big Beach Brewing Co.',
          "bcbs-link": 'https: //www.bigbeachbrewing.com/copy-of-home',
          "best-dog-friendly-spot": 'Gulf Shores Dog Park',
          "bdfs-link": 'https: //www.gulfshores.com/things-to-do/gulf-shores-dog-park/',
          "best-outdoorsy-spot": 'Gulf State Park',
          "bos-link": 'https: //www.alapark.com/parks/gulf-state-park',
          "best-local-fast-food-spot": `Foosackly's`,
          "blffs-link": 'http: //foosacklys.net'
      },
      {
          id: '3',
          state: 'Alaska',
          city: 'Fairbanks',
          "best-cheap-beer-spot": 'The Boatel',
          "bcbs-link": 'https: //www.facebook.com/akboatel/',
          "best-dog-friendly-spot": 'Fairbanks Dog Park',
          "bdfs-link": 'http: //www.fairbanksdogpark.org',
          "best-outdoorsy-spot": 'Arctic National Wildlife Refuge',
          "bos-link": 'https: //www.fws.gov/refuge/arctic/',
          "best-local-fast-food-spot": 'The Crepery',
          "blffs-link": 'https: //www.thecrepery.net'
      },
      {
          id: '4',
          state: 'Alaska',
          city: 'Juneau',
          "best-cheap-beer-spot": 'The Narrows Bar',
          "bcbs-link": 'https: //www.facebook.com/pg/thenarrowsbaralaska/reviews/?ref=page_internal',
          "best-dog-friendly-spot": 'Mendenhall Wetlands State Game Refuge',
          "bdfs-link": 'http: //www.adfg.alaska.gov/index.cfm?adfg=mendenhallwetlands.main',
          "best-outdoorsy-spot": 'Eagle Beach State Recreation Area',
          "bos-link": 'http: //dnr.alaska.gov/parks/aspunits/southeast/eaglebeachsra.htm',
          "best-local-fast-food-spot": 'The Salmon Spot',
          "blffs-link": 'http: //aksalmonspot.com'
      },
      {
          id: '5',
          state: 'Arizona',
          city: 'Sedona',
          "best-cheap-beer-spot": 'Sedona Beer Company',
          "bcbs-link": 'https: //www.sedonabeerco.com',
          "best-dog-friendly-spot": 'Sedona Dog Park',
          "bdfs-link": 'https: //www.sedonaaz.gov/your-government/departments/parks-recreation/city-parks/dog-park',
          "best-outdoorsy-spot": 'Cathedral Rock Trail',
          "bos-link": 'Cathedral Rock Trail, Sedona, AZ 86351',
          "best-local-fast-food-spot": 'Tortas de Fuego',
          "blffs-link": 'https: //www.tortasdefuegosedona.com'
      },
      {
          id: '6',
          state: 'Arizona',
          city: 'Tuscon',
          "best-cheap-beer-spot": 'Arizona Beer House',
          "bcbs-link": 'https: //www.arizonabeerhouse.com',
          "best-dog-friendly-spot": 'Mikos Corner Playground Dog Park',
          "bdfs-link": 'https: //www.tucsonaz.gov/parks/dog-parks',
          "best-outdoorsy-spot": 'Brandi Fenton Memorial Park',
          "bos-link": 'https: //webcms.pima.gov/cms/one.aspx?portalId=169&pageId=1367',
          "best-local-fast-food-spot": 'Jimmys Pita and Poke',
          "blffs-link": 'https: //www.jimmys2go.com'
      },
      {
          id: '7',
          state: 'Arkansas',
          city: 'Fayetville',
          "best-cheap-beer-spot": 'Dickson Street Pub',
          "bcbs-link": 'http: //www.dicksonstreetpub.com',
          "best-dog-friendly-spot": 'Gulley Park',
          "bdfs-link": 'https: //www.fayetteville-ar.gov/facilities/facility/details/Gulley-Park-Pavilion-67',
          "best-outdoorsy-spot": 'Mt. Sequoyah Woods Trail',
          "bos-link": 'https: //www.fayetteville-ar.gov/facilities/facility/details/Mt-Sequoyah-Woods-Trail-23',
          "best-local-fast-food-spot": 'CJs Butcher Boys',
          "blffs-link": 'https: //www.butcherboyburger.com'
      },
      {
        id: '8',
        state: 'Arkansas',
        city: 'Little Rock',
        "best-cheap-beer-spot": 'Stones Throw Brewing',
        "bcbs-link": 'http: //www.stonesthrowbeer.com',
        "best-dog-friendly-spot": 'Bark Bar',
        "bdfs-link": 'https: //barkbar.com',
        "best-outdoorsy-spot": 'Pinnacle Mountain State Park',
        "bos-link": 'https: //www.arkansasstateparks.com/parks/pinnacle-mountain-state-park',
        "best-local-fast-food-spot": 'Davids Burgers',
        "blffs-link": 'https: //www.davidsburgers.com'
      },
      {
        id: '9',
        state: 'California',
        city: 'San Diego',
        "best-cheap-beer-spot": 'Pizza Port',
        "bcbs-link": 'https: //www.pizzaport.com/brewpubs/ocean-beach',
        "best-dog-friendly-spot": 'Fiesta Island Dog Park',
        "bdfs-link": 'https: //www.sandiego.gov/park-and-recreation/parks/regional/missionbay/fiestaisland',
        "best-outdoorsy-spot": 'La Jolla Cove',
        "bos-link": 'https: //www.lajolla.com/guides/la-jolla-cove/',
        "best-local-fast-food-spot": 'Rubios Coastal Grill',
        "blffs-link": 'https: //www.rubios.com/restaurant-locations/california/san-diego/mission-bay'
      },
      {
        id: '10',
        state: 'California',
        city: 'San Francisco',
        "best-cheap-beer-spot": 'Cellarmaker Brewing',
        "bcbs-link": 'https: //cellarmakerbrewing.com',
        "best-dog-friendly-spot": 'Stem Grove Dog Park',
        "bdfs-link": '100 Vale Ave, San Francisco, CA 94132',
        "best-outdoorsy-spot": 'Golden Gate Park',
        "bos-link": 'https: //sfrecpark.org/770/Golden-Gate-Park',
        "best-local-fast-food-spot": 'Pearls Deluxe Burgers',
        "blffs-link": 'https: //pearlsdeluxe.com'
      },
      {
        id: '11',
        state: 'Colorado',
        city: 'Durango',
        "best-cheap-beer-spot": 'Ska Brewing',
        "bcbs-link": 'https: //skabrewing.com/?doing_wp_cron=1610521145.2479219436645507812500',
        "best-dog-friendly-spot": 'Durango Off Leash Dog Park',
        "bdfs-link": 'US-160 & Hwy 550, Durango, CO 81301',
        "best-outdoorsy-spot": 'The Colorado Trail',
        "bos-link": 'https: //coloradotrail.org',
        "best-local-fast-food-spot": 'Zia Taqueria',
        "blffs-link": 'https: //ziataqueria.com'
      },
      {
        id: '12',
        state: 'Colorado',
        city: 'Denver',
        "best-cheap-beer-spot": 'The 1up Arcade Bar',
        "bcbs-link": 'https: //the1uparcadebar.com/lodo/',
        "best-dog-friendly-spot": 'Stapleton Off Leash Dog Park',
        "bdfs-link": 'https: //www.denvergov.org/content/denvergov/en/denver-parks-and-recreation/parks/city-parks/dog-parks.html',
        "best-outdoorsy-spot": 'Rocky Mountain National Park',
        "bos-link": 'https: //www.nps.gov/romo/index.htm',
        "best-local-fast-food-spot": 'Crown Burgers',
        "blffs-link": 'http: //www.crownburgers.org'
      },
      {
        id: '13',
        state: 'Connecticut',
        city: 'Stamford',
        "best-cheap-beer-spot": 'Half Full Brewery',
        "bcbs-link": 'https: //halffullbrewery.com',
        "best-dog-friendly-spot": 'Stamford Dog Park',
        "bdfs-link": 'http: //www.stamforddogpark.com',
        "best-outdoorsy-spot": 'Mianus River Park',
        "bos-link": 'https: //www.stamfordct.gov/city-parks/pages/mianus-river-park',
        "best-local-fast-food-spot": 'PUAG',
        "blffs-link": 'https: //www.facebook.com/Puageats/'
      },
      {
        id: '14',
        state: 'Connecticut',
        city: 'New Haven',
        "best-cheap-beer-spot": 'Cafe Nine',
        "bcbs-link": 'https: //www.cafenine.com',
        "best-dog-friendly-spot": 'Edgewood Dog Park',
        "bdfs-link": 'https: //www.visitconnecticut.com/newhaven_southcentral/dog-parks-off-leash/',
        "best-outdoorsy-spot": 'Sleeping Giant State Park',
        "bos-link": 'https: //portal.ct.gov/DEEP/State-Parks/Parks/Sleeping-Giant-State-Park',
        "best-local-fast-food-spot": 'The Halal Guys',
        "blffs-link": 'https: //thehalalguys.com'
      },
      {
        id: '15',
        state: 'Delaware',
        city: 'Wilmington',
        "best-cheap-beer-spot": 'Wilmington Brew Works',
        "bcbs-link": 'https: //wilmingtonbrewworks.com',
        "best-dog-friendly-spot": 'Brandywine Park',
        "bdfs-link": '1080 N Park Dr, Wilmington, DE 19802',
        "best-outdoorsy-spot": 'Alapocas Run State Park',
        "bos-link": 'https: //destateparks.com/FieldsStreams/Alapocas',
        "best-local-fast-food-spot": 'El Diablo Burritos',
        "blffs-link": 'https: //www.eldiabloburritos.com'
      },
      {
        id: '16',
        state: 'Delaware',
        city: 'Newark',
        "best-cheap-beer-spot": 'Two Stones Pub',
        "bcbs-link": 'https: //twostonespub.com',
        "best-dog-friendly-spot": 'New Castle County Bark Park',
        "bdfs-link": 'https: //www.nccde.org/1537/Glasgow-Park',
        "best-outdoorsy-spot": 'Rittenhouse Park',
        "bos-link": 'https: //newarkde.gov/468/Rittenhouse-Park',
        "best-local-fast-food-spot": 'Wayback Burgers',
        "blffs-link": 'https: //waybackburgers.com/?y_source=1_MTM4NTMyMTAtNzE1LWxvY2F0aW9uLndlYnNpdGU%3D'
      },
      {
        id: '17',
        state: 'Florida',
        city: 'St. Petersburg',
        "best-cheap-beer-spot": 'Five Bucks Drinkery',
        "bcbs-link": 'https: //fivebucksdrinkery.com',
        "best-dog-friendly-spot": 'Kenwood Dog Park',
        "bdfs-link": '401 20th St N, St. Petersburg, FL 33713',
        "best-outdoorsy-spot": 'Sawgrass Lake Park',
        "bos-link": 'http: //www.pinellascounty.org/park/16_Sawgrass.htm',
        "best-local-fast-food-spot": 'EVOS Feel Great Food',
        "blffs-link": 'https: //evos.com'
      },
      {
        id: '18',
        state: 'Florida',
        city: 'Key West',
        "best-cheap-beer-spot": 'The Bull',
        "bcbs-link": 'http: //bullkeywest.org',
        "best-dog-friendly-spot": 'Higgs Beach Dog Park',
        "bdfs-link": 'http: //www.monroecounty-fl.gov/235/Higgs-Beach',
        "best-outdoorsy-spot": 'Fort Zachary Taylor Historic State Park',
        "bos-link": 'https: //www.floridastateparks.org/parks-and-trails/fort-zachary-taylor-historic-state-park',
        "best-local-fast-food-spot": 'Kims Cuban',
        "blffs-link": 'https: //kimskubankw.com'
      },
      {
        id: '19',
        state: 'Georgia',
        city: 'Atlanta',
        "best-cheap-beer-spot": 'Sweetwater Brewing Company',
        "bcbs-link": 'https: //www.sweetwaterbrew.com',
        "best-dog-friendly-spot": 'Piedmont Dog Park',
        "bdfs-link": 'https: //www.piedmontpark.org/dog-parks/',
        "best-outdoorsy-spot": 'Cascade Springs Nature Preserve',
        "bos-link": 'https: //www.atlantaga.gov/government/departments/parks-recreation/office-of-parks/list-of-parks-alphabetical',
        "best-local-fast-food-spot": 'The Varsity',
        "blffs-link": 'https: //thevarsity.com/locations?action=view&store_id=9'
      },
      {
        id: '20',
        state: 'Georgia',
        city: 'Savannah',
        "best-cheap-beer-spot": 'The Warehouse Bar and Grill',
        "bcbs-link": 'https: //www.thewarehousebarandgrille.com',
        "best-dog-friendly-spot": 'Herty Pines Dog Park',
        "bdfs-link": 'n, Bee Rd, Savannah, GA 31404',
        "best-outdoorsy-spot": 'Skidaway Island State Park',
        "bos-link": 'https: //gastateparks.org/SkidawayIsland',
        "best-local-fast-food-spot": 'Spudnik',
        "blffs-link": 'https: //www.spudniksavannah.com'
      },
      {
        id: '21',
        state: 'Hawaii',
        city: 'Honolulu',
        "best-cheap-beer-spot": 'Growler Hawaii',
        "bcbs-link": 'https: //www.growlerhawaii.com',
        "best-dog-friendly-spot": 'Diamond Head Bark Park',
        "bdfs-link": '4155 Diamond Head Rd, Honolulu, HI 96816',
        "best-outdoorsy-spot": 'Kahanamoku Beach',
        "bos-link": 'https: //www.gohawaii.com',
        "best-local-fast-food-spot": 'Jets',
        "blffs-link": 'https: //www.jetsislandfood.com'
      },
      {
        id: '22',
        state: 'Hawaii',
        city: 'Kailua-Kona',
        "best-cheap-beer-spot": 'Kona Brewing Hawaii',
        "bcbs-link": 'https: //www.konabrewinghawaii.com',
        "best-dog-friendly-spot": 'Enchanted Lake Community Park',
        "bdfs-link": '770 Keolu Dr, Kailua, HI 96734',
        "best-outdoorsy-spot": 'Old Kona Airport State Recreaion Area',
        "bos-link": '75-5560 Kuakini Hwy, Kailua-Kona, HI 96740',
        "best-local-fast-food-spot": 'Ultimate Burger',
        "blffs-link": 'https: //www.ultimateburger.net'
      },
      {
        id: '23',
        state: 'Idaho',
        city: `Coeur d'Alene`,
        "best-cheap-beer-spot": 'The Growler Guys',
        "bcbs-link": 'https: //www.thegrowlerguys.com/locations/coeur-dalene-idaho/',
        "best-dog-friendly-spot": 'Central Bark Dog Park',
        "bdfs-link": 'https: //www.cdaid.org/737/departments/parks/all-parks/central-bark-dog-park',
        "best-outdoorsy-spot": 'Tubbs Hill',
        "bos-link": 'https: //www.alltrails.com/us/idaho/coeur-d-alene--2',
        "best-local-fast-food-spot": 'Rogers Ice Cream and Burgers',
        "blffs-link": 'http: //www.rogersicecreamburgers.com'
      },
      {
        id: '24',
        state: 'Idaho',
        city: 'Twin Falls',
        "best-cheap-beer-spot": 'Koto Brewing Co',
        "bcbs-link": 'https: //koto.beer',
        "best-dog-friendly-spot": 'Harmon Park',
        "bdfs-link": 'https: //www.tfid.org',
        "best-outdoorsy-spot": 'Shoshone Falls Park',
        "bos-link": 'https: //www.tfid.org/309/Shoshone-Falls',
        "best-local-fast-food-spot": 'Burnt Lemon Grill',
        "blffs-link": 'http: //ww7.burntlemongrill.com'
      },
      {
        id: '25',
        state: 'Illinois',
        city: 'Chicago',
        "best-cheap-beer-spot": 'Bangers and Lace',
        "bcbs-link": 'http: //www.bangersandlacechicago.com',
        "best-dog-friendly-spot": 'Wiggly Field Dog Park',
        "bdfs-link": 'https: //www.chicago.gov/city/en.html',
        "best-outdoorsy-spot": 'North Avenue Beach',
        "bos-link": 'https: //www.chicagoparkdistrict.com/parks-facilities/north-avenue-beach/',
        "best-local-fast-food-spot": 'Portillos Hot Dogs',
        "blffs-link": 'https: //www.portillos.com/locations/chicago/?utm_source=google&utm_medium=yext&utm_campaign=website'
      },
      {
        id: '26',
        state: 'Illinois',
        city: 'Springfield',
        "best-cheap-beer-spot": 'Craft Beer Bar',
        "bcbs-link": 'https: //www.craftbeerbar-il.com',
        "best-dog-friendly-spot": 'Washington Park',
        "bdfs-link": 'https: //springfieldparks.org/parks/washington/',
        "best-outdoorsy-spot": 'Lincoln Memorial Garden and Nature Center',
        "bos-link": 'http: //lincolnmemorialgarden.org',
        "best-local-fast-food-spot": 'Krekels Custard',
        "blffs-link": 'https: //www.krekelscustard.com'
      },
      {
        id: '27',
        state: 'Indiana',
        city: 'Indianapolis',
        "best-cheap-beer-spot": 'Dorman Street',
        "bcbs-link": 'http: //dormanstreet.com/bar/',
        "best-dog-friendly-spot": 'Fort Harrison State Park Dog Park',
        "bdfs-link": 'https: //www.in.gov/dnr/parklake/2982.htm',
        "best-outdoorsy-spot": 'Morgan Monroe State Forest',
        "bos-link": 'https: //www.in.gov/dnr/forestry/4816.htm',
        "best-local-fast-food-spot": 'Jaggers',
        "blffs-link": 'https: //www.eatjaggers.com'
      },
      {
        id: '28',
        state: 'Indiana',
        city: 'Carmel',
        "best-cheap-beer-spot": 'Upland Carmel Taphouse',
        "bcbs-link": 'https: //uplandbeer.com/carmel/',
        "best-dog-friendly-spot": 'Central Dog Park',
        "bdfs-link": 'https: //www.carmelclayparks.com/parks/central-dog-park/',
        "best-outdoorsy-spot": 'Monon Trail',
        "bos-link": 'https: //www.visithamiltoncounty.com/things-to-do/outdoors/monon-trail/',
        "best-local-fast-food-spot": 'Punch Burger',
        "blffs-link": 'http: //www.punchburger.com'
      },
      {
        id: '29',
        state: 'Iowa',
        city: 'Des Moines',
        "best-cheap-beer-spot": 'El Bait Shop',
        "bcbs-link": 'https: //elbaitshop.com',
        "best-dog-friendly-spot": 'Windsor Heights Dog Park',
        "bdfs-link": '6601 Center St, Windsor Heights, IA 50324',
        "best-outdoorsy-spot": 'Walnut Woods State Park',
        "bos-link": 'https: //www.iowadnr.gov/Places-to-Go/State-Parks/Iowa-State-Parks',
        "best-local-fast-food-spot": 'George The Chili King Drive-In',
        "blffs-link": 'http: //www.georgethechiliking.com'
      },
      {
        id: '30',
        state: 'Iowa',
        city: 'Iowa City',
        "best-cheap-beer-spot": 'Big Grove Brewery',
        "bcbs-link": 'https: //biggrovebrewery.com',
        "best-dog-friendly-spot": 'Thornberry Off-Leash Dog Park',
        "bdfs-link": 'https: //www.icgov.org/city-government/departments-and-divisions/parks-and-recreation/parks-and-forestry/parks/parks-17',
        "best-outdoorsy-spot": 'Hickory Hill Park',
        "bos-link": 'https: //www.icgov.org/hickory-hill-park',
        "best-local-fast-food-spot": 'Hamburger Inn No. 2',
        "blffs-link": 'https: //www.hamburginn2.com'
      },
      {
        id: '31',
        state: 'Kansas',
        city: 'Topeka',
        "best-cheap-beer-spot": 'Blind Tiger Brewery and Restaurant',
        "bcbs-link": 'https: //www.blindtiger.com',
        "best-dog-friendly-spot": 'Gage Park',
        "bdfs-link": 'http: //parks.snco.us',
        "best-outdoorsy-spot": 'Kaw River State Park',
        "bos-link": 'https: //ksoutdoors.com/State-Parks/Locations/Kaw-River',
        "best-local-fast-food-spot": 'Bobos Drive-In',
        "blffs-link": 'https: //m.facebook.com/Bobos-Drive-In-269473363065750/'
      },
      {
        id: '32',
        state: 'Kansas',
        city: 'Wichita',
        "best-cheap-beer-spot": 'Augustino Brewing Company',
        "bcbs-link": 'https: //augustinobrew.com',
        "best-dog-friendly-spot": 'Chapin Park',
        "bdfs-link": 'https: //www.wichita.gov/ParkandRec/CityParks/Pages/Chapin.aspx',
        "best-outdoorsy-spot": 'Sedgwick County Park',
        "bos-link": 'https: //www.sedgwickcounty.org',
        "best-local-fast-food-spot": 'West Street Burgers',
        "blffs-link": 'https: //west-street-burgers.business.site/?utm_source=gmb&utm_medium=referral'
      },
      {
        id: '33',
        state: 'Kentucky',
        city: 'Bowling Green',
        "best-cheap-beer-spot": 'Pub By Novo',
        "bcbs-link": 'https: //www.pubbynovo.com',
        "best-dog-friendly-spot": 'Bark Park at H.P. Thomas Park',
        "bdfs-link": 'https: //www.bgky.org/bgpr/parks/34',
        "best-outdoorsy-spot": 'Lost River Cave',
        "bos-link": 'https: //www.lostrivercave.org',
        "best-local-fast-food-spot": 'Krystal',
        "blffs-link": 'https: //locations.krystal.com/ky/bowling-green/2704-scottsville-rd'
      },
      {
        id: '34',
        state: 'Kentucky',
        city: 'Louisville',
        "best-cheap-beer-spot": 'Nachbar',
        "bcbs-link": 'https: //m.facebook.com/nach.bar.1',
        "best-dog-friendly-spot": 'Morton Avenue Dog Park',
        "bdfs-link": 'https: //www.facebook.com/pages/Morton-Street-Free-Dog-Park/122051571189545',
        "best-outdoorsy-spot": 'Jefferson Memorial Forest',
        "bos-link": 'https: //louisvilleky.gov/government/jefferson-memorial-forest',
        "best-local-fast-food-spot": 'Chicken King of Louisville',
        "blffs-link": 'https: //www.chickenkinglouisville.com'
      },

    {
      id: '35',
      state: 'Louisiana',
      city: 'New Orleans',
      "best-cheap-beer-spot": 'Erin Rose',
      "bcbs-link": 'http: //www.erinrosebar.com',
      "best-dog-friendly-spot": 'NOLA City Bark',
      "bdfs-link": 'http: //www.nolacitybark.org',
      "best-outdoorsy-spot": 'Coconut Beach',
      "bos-link": 'https: //coconutbeachla.com',
      "best-local-fast-food-spot": 'Chicken King of Louisville',
      "blffs-link": 'https: //shop.cafedumonde.com'
    },
    {
      id: '36',
      state: 'Louisiana',
      city: 'Baton Rouge',
      "best-cheap-beer-spot": 'The Radio Bar',
      "bcbs-link": 'https: //m.facebook.com/theradiobar/',
      "best-dog-friendly-spot": 'Raising Canes Dog Park',
      "bdfs-link": 'https: //www.brec.org/index.cfm/park/detail/204',
      "best-outdoorsy-spot": 'Bluebonnet Swamp Nature Center',
      "bos-link": 'https: //www.brec.org/index.cfm/park/BluebonnetSwamp',
      "best-local-fast-food-spot": 'Po-Boy Express',
      "blffs-link": 'http: //www.poboyexpress.com'
    },
    {
      id: '37',
      state: 'Maine',
      city: 'Portland',
      "best-cheap-beer-spot": 'The Thirsty Pig',
      "bcbs-link": 'http: //www.thirstypigportland.com',
      "best-dog-friendly-spot": 'Bug Light Park',
      "bdfs-link": 'https: //www.southportland.org',
      "best-outdoorsy-spot": 'East End Beach',
      "bos-link": 'http: //www.portlandmaine.gov',
      "best-local-fast-food-spot": 'B.Good',
      "blffs-link": 'https: //www.bgood.com/our-menu'
    },
    {
      id: '38',
      state: 'Maine',
      city: 'Bar Harbor',
      "best-cheap-beer-spot": 'Dog & Pony Tavern',
      "bcbs-link": 'https: //www.dogandponytavern.com',
      "best-dog-friendly-spot": 'Agamont Park',
      "bdfs-link": 'Bar Harbor, ME 04609',
      "best-outdoorsy-spot": 'Acadia National Park',
      "bos-link": 'https: //www.nps.gov/acad/index.htm',
      "best-local-fast-food-spot": 'Downeast Deli and Box Lunch Co.',
      "blffs-link": 'https: //downeastdeli.com'
    },
    {
      id: '39',
      state: 'Maryland',
      city: 'Baltimore',
      "best-cheap-beer-spot": 'Suspended Brewing Company',
      "bcbs-link": 'https: //www.suspendedbrewing.com',
      "best-dog-friendly-spot": 'Patterson Dog Park',
      "bdfs-link": 'https: //m.facebook.com/PattersonParkDogPark',
      "best-outdoorsy-spot": 'Druid Hill Park',
      "bos-link": 'https: //bcrp.baltimorecity.gov',
      "best-local-fast-food-spot": 'Baltimores Best Wings',
      "blffs-link": '1405 E Cold Spring Ln, Baltimore, MD 21239'
    },
    {
      id: '40',
      state: 'Maryland',
      city: 'Annapolis',
      "best-cheap-beer-spot": 'Davis Pub',
      "bcbs-link": 'https: //davispub.com',
      "best-dog-friendly-spot": 'Quiet Waters Park',
      "bdfs-link": 'https: //www.aacounty.org/departments/recreation-parks/parks/quiet-waters/',
      "best-outdoorsy-spot": 'Jonas and Anne Catharine Green Park',
      "bos-link": 'https: //www.aacounty.org/locations-and-directions/jonas-and-anne-catharine-green-park',
      "best-local-fast-food-spot": 'Cheeburger',
      "blffs-link": 'https: //www.cheeburger.com'
    },
    {
      id: '41',
      state: 'Massachusetts',
      city: 'Boston',
      "best-cheap-beer-spot": 'The Tam',
      "bcbs-link": 'https: //www.thetamboston.com',
      "best-dog-friendly-spot": 'South Boston Bark Park',
      "bdfs-link": 'http: //www.sbbarkpark.org',
      "best-outdoorsy-spot": 'Boston Harbor Islands',
      "bos-link": 'https: //www.bostonharborislands.org',
      "best-local-fast-food-spot": 'Tasty Burger',
      "blffs-link": 'https: //www.tastyburger.com'
    },
    {
      id: '42',
      state: 'Massachusetts',
      city: 'Cambridge',
      "best-cheap-beer-spot": 'The Peoples Republik',
      "bcbs-link": 'http: //www.peoplesrepublik.com',
      "best-dog-friendly-spot": 'Danehy Dog Park',
      "bdfs-link": '99 Sherman St, Cambridge, MA 02138',
      "best-outdoorsy-spot": 'Cambridge Common',
      "bos-link": 'https: //www.cambridgema.gov/CDD/parks/parksinfo/Parks/cambridgecommon',
      "best-local-fast-food-spot": 'Clover Food Lab',
      "blffs-link": 'https: //www.cloverfoodlab.com'
    },
    {
      id: '43',
      state: 'Michigan',
      city: 'Detroit',
      "best-cheap-beer-spot": 'Bronx Bar',
      "bcbs-link": '4476 2nd Ave, Detroit, MI 48201',
      "best-dog-friendly-spot": 'Balduck Park',
      "bdfs-link": 'https: //detroitmi.gov/departments/parks-recreation',
      "best-outdoorsy-spot": 'Detroit Riverfront',
      "bos-link": 'https: //detroitriverfront.org',
      "best-local-fast-food-spot": 'Royale With Cheese',
      "blffs-link": 'https: //royalewithcheese.menu'
    },
    {
      id: '44',
      state: 'Michigan',
      city: 'Grand Rapids',
      "best-cheap-beer-spot": 'Meanwhile Bar',
      "bcbs-link": 'http: //meanwhilebar.com',
      "best-dog-friendly-spot": 'Hillcrest Dog Park',
      "bdfs-link": 'https: //www.grandrapidsmi.gov/Home',
      "best-outdoorsy-spot": 'Blanford Nature Preserve',
      "bos-link": 'https: //blandfordnaturecenter.org',
      "best-local-fast-food-spot": 'One Stop Coney Shop',
      "blffs-link": 'https: //www.onestopconey.com'
    },
    {
      id: '45',
      state: 'Minnesota',
      city: 'Minneapolis',
      "best-cheap-beer-spot": 'Town Hall Brewery',
      "bcbs-link": 'https: //townhallbrewery.com',
      "best-dog-friendly-spot": 'Minnehaha Dog Park',
      "bdfs-link": 'https: //www.minneapolisparks.org/parks__destinations/dog_parks/minnehaha_off-leash_dog_park/',
      "best-outdoorsy-spot": 'Hyland Lake Park',
      "bos-link": 'https: //www.threeriversparks.org/location/hyland-lake-park-reserve',
      "best-local-fast-food-spot": 'World Street Kitchen',
      "blffs-link": 'https: //www.eatwsk.com'
    },
    {
      id: '46',
      state: 'Minnesota',
      city: 'Saint Paul',
      "best-cheap-beer-spot": 'Saint Paul Brewing',
      "bcbs-link": 'https: //www.stpaulbrewing.com',
      "best-dog-friendly-spot": 'High Bridge Dog Park',
      "bdfs-link": 'https: //www.stpaul.gov/facilities/high-bridge-dog-park',
      "best-outdoorsy-spot": 'Hidden Falls Regional Park',
      "bos-link": 'https: //www.stpaul.gov/facilities/hidden-falls-regional-park',
      "best-local-fast-food-spot": 'The Coop',
      "blffs-link": 'http: //thecooprestaurant.com'
    },
    {
      id: '47',
      state: 'Mississippi',
      city: 'Jackson',
      "best-cheap-beer-spot": 'Hops and Habanas',
      "bcbs-link": 'https: //hopsandhabanas.com',
      "best-dog-friendly-spot": 'Parham Bridges Park',
      "bdfs-link": 'https: //www.jacksonms.gov/departments/parks-recreation-department/',
      "best-outdoorsy-spot": 'LeFleurs Bluff State Park',
      "bos-link": 'https: //www.mdwfp.com/parks-destinations/state-parks/lefleurs-bluff',
      "best-local-fast-food-spot": 'Stamps Super Burgers',
      "blffs-link": 'https: //stamps-super-burgers.business.site/?m=true'
    },
    {
      id: '48',
      state: 'Mississippi',
      city: 'Biloxi',
      "best-cheap-beer-spot": 'Biloxi Brewing Company',
      "bcbs-link": '186 Bohn St, Biloxi, MS 39530',
      "best-dog-friendly-spot": 'Hiller Park',
      "bdfs-link": 'https: //biloxi.ms.us/residents/parks-recreation/parks/hiller/',
      "best-outdoorsy-spot": 'Biloxi Beach',
      "bos-link": 'https: //biloxi.ms.us',
      "best-local-fast-food-spot": 'Burger Burger',
      "blffs-link": 'http: //sablich.com/bb/index.php'
    },
    {
      id: '49',
      state: 'Missouri',
      city: 'Kansas City',
      "best-cheap-beer-spot": 'MO Brew',
      "bcbs-link": 'http: //mobrewkc.com',
      "best-dog-friendly-spot": 'Swope Dog Park',
      "bdfs-link": '5051 E Gregory Blvd, Kansas City, MO 64132',
      "best-outdoorsy-spot": 'Penn Valley Park',
      "bos-link": 'https: //kcparks.org',
      "best-local-fast-food-spot": 'In-A-Tub',
      "blffs-link": '8174 NW Prairie View Rd, Kansas City, MO 64151'
    },
    {
      id: '50',
      state: 'Missouri',
      city: 'St. Louis',
      "best-cheap-beer-spot": 'Hair of the Dog',
      "bcbs-link": '212 Washington Ave, St. Louis, MO 63103',
      "best-dog-friendly-spot": 'Willmore Park',
      "bdfs-link": 'https: //www.stlouis-mo.gov/government/departments/parks/parks/browse-parks/view-park.cfm?parkID=93&parkName=Willmore',
      "best-outdoorsy-spot": 'Forest Park',
      "bos-link": 'https: //forestparkmap.org',
      "best-local-fast-food-spot": 'Fort Taco',
      "blffs-link": 'http: //www.forttaco.com'
    },
    {
      id: '51',
      state: 'Montana',
      city: 'Helena',
      "best-cheap-beer-spot": 'Lewis and Clark Tap Room',
      "bcbs-link": 'https: //lctaproom.com',
      "best-dog-friendly-spot": 'Paws Park',
      "bdfs-link": '1250 N Last Chance Gulch, Helena, MT 59601',
      "best-outdoorsy-spot": 'Mount Helena',
      "bos-link": 'https: //www.visitmt.com/listings/general/city-park/mount-helena-city-park.html',
      "best-local-fast-food-spot": 'Planet Gyros',
      "blffs-link": 'https: //planetgyroshelena.com'
    },
    {
      id: '52',
      state: 'Montana',
      city: 'Missoula',
      "best-cheap-beer-spot": 'The Rhino',
      "bcbs-link": 'https: //rhinomontana.com',
      "best-dog-friendly-spot": 'Jacobs Islan Offleash Dog Park',
      "bdfs-link": 'http: //www.ci.missoula.mt.us/623/Where-Can-My-Dog-be-Off-Leash',
      "best-outdoorsy-spot": 'Snowbowl',
      "bos-link": 'https: //www.montanasnowbowl.com',
      "best-local-fast-food-spot": 'Hoagieville',
      "blffs-link": 'https: //hoagieville.com'
    },
    {
      id: '53',
      state: 'Nebraska',
      city: 'Omaha',
      "best-cheap-beer-spot": 'Beertopia',
      "bcbs-link": 'http: //beercornerusa.com/beertopia/',
      "best-dog-friendly-spot": 'Hefflinger Dog Park',
      "bdfs-link": 'Old Maple Rd & N 112th Ave, Omaha, NE 68164',
      "best-outdoorsy-spot": 'Lauritzen Gardens/Kenefick Park',
      "bos-link": 'https: //www.lauritzengardens.org',
      "best-local-fast-food-spot": 'Broncos',
      "blffs-link": 'https: //www.broncoburgers.com'
    },
    {
      id: '54',
      state: 'Nebraska',
      city: 'Lincoln',
      "best-cheap-beer-spot": 'Zipline Beer Hall',
      "bcbs-link": 'https: //ziplinebrewing.com',
      "best-dog-friendly-spot": 'Holmes Lake Dog Park',
      "bdfs-link": 'http: //www.lincolndogparks.org',
      "best-outdoorsy-spot": 'Sunken Gardens',
      "bos-link": 'https: //www.lincolnparks.org/what_we_do/tributes-memorials/sunken-gardens.html',
      "best-local-fast-food-spot": 'Runza Restaurant',
      "blffs-link": 'https: //www.runza.com'
    },
    {
      id: '55',
      state: 'Nevada',
      city: 'Las Vegas',
      "best-cheap-beer-spot": 'Dinos Lounge',
      "bcbs-link": '1516 S Las Vegas Blvd, Las Vegas, NV 89104',
      "best-dog-friendly-spot": 'Barkin Basin Park',
      "bdfs-link": 'https: //www.lasvegasnevada.gov',
      "best-outdoorsy-spot": 'Red Rock Canyon Conservation Area',
      "bos-link": 'https: //www.redrockcanyonlv.org',
      "best-local-fast-food-spot": 'Rallys',
      "blffs-link": 'https: //locations.rallys.com/nv/las-vegas/1900-e.-charleston-blvd.?y_source=1_MzI0ODc1Mi03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D'
    },
    {
      id: '56',
      state: 'Nebraska',
      city: 'Reno',
      "best-cheap-beer-spot": 'The Depot Craft Brewery Distillery',
      "bcbs-link": 'https: //thedepotreno.com',
      "best-dog-friendly-spot": 'Link Piazzo Dog Park',
      "bdfs-link": '4740 Parkway Dr, Reno, NV 89502',
      "best-outdoorsy-spot": 'Hunter Creek Trailhead',
      "bos-link": 'Reno, NV 89519',
      "best-local-fast-food-spot": 'Scoopers',
      "blffs-link": '4040 Kietzke Ln, Reno, NV 89502'
    },
    {
      id: '57',
      state: 'New Hampshire',
      city: 'Nashua',
      "best-cheap-beer-spot": 'Spyglass Brewing Company',
      "bcbs-link": 'https: //www.spyglassbrewing.com/age?url=https%3A%2F%2Fwww.spyglassbrewing.com%2F',
      "best-dog-friendly-spot": 'Mine Falls Park',
      "bdfs-link": 'https: //www.nashuanh.gov/491/Mine-Falls-Park',
      "best-outdoorsy-spot": 'Mine Falls Park',
      "bos-link": 'https: //www.nashuanh.gov/491/Mine-Falls-Park',
      "best-local-fast-food-spot": 'Nortons Classic Cafe',
      "blffs-link": 'http: //www.nortonsclassiccafe.com'
    },
    {
      id: '58',
      state: 'New Hampshire',
      city: 'Portsmouth',
      "best-cheap-beer-spot": 'Portsmouth Brewery',
      "bcbs-link": 'https: //portsmouthbrewery.com',
      "best-dog-friendly-spot": 'Dog Park',
      "bdfs-link": 'https: //www.cityofportsmouth.com',
      "best-outdoorsy-spot": 'Prescott Park',
      "bos-link": 'https: //www.cityofportsmouth.com/prescottpark',
      "best-local-fast-food-spot": 'Lexies Joint',
      "blffs-link": 'https: //www.peaceloveburgers.com'
    },
    {
      id: '59',
      state: 'New Jersey',
      city: 'Jersey City',
      "best-cheap-beer-spot": 'Departed Soles Brewing Company',
      "bcbs-link": 'https: //www.departedsoles.com',
      "best-dog-friendly-spot": 'Morris Canal Park',
      "bdfs-link": 'https: //www.state.nj.us/dep/parksandforests/parks/liberty_state_park/liberty_morriscanal.html',
      "best-outdoorsy-spot": 'Liberty State Park',
      "bos-link": 'https: //www.visithudson.org/things-to-do/parksnature/',
      "best-local-fast-food-spot": 'Chicken Delight',
      "blffs-link": 'https: //www.chickendelightjc.com'
    },
    {
      id: '60',
      state: 'New Jersey',
      city: 'Hoboken',
      "best-cheap-beer-spot": 'The Ale House',
      "bcbs-link": 'https: //www.facebook.com/alehousehoboken',
      "best-dog-friendly-spot": 'Viaduct Dog Park',
      "bdfs-link": 'https: //www.hobokennj.gov',
      "best-outdoorsy-spot": 'Liberty State Park',
      "bos-link": 'https: //www.visithudson.org/things-to-do/parksnature/',
      "best-local-fast-food-spot": 'Chicken Delight',
      "blffs-link": 'https: //www.chickendelightjc.com'
    },
    {
      id: '61',
      state: 'New Mexico',
      city: 'Santa Fe',
      "best-cheap-beer-spot": 'Desert Dogs Brewery and Cidery',
      "bcbs-link": 'https: //www.facebook.com/desertdogsbrewery/',
      "best-dog-friendly-spot": 'Frank S. Ortiz Dog Park',
      "bdfs-link": 'https: //thedogparkproject.org/index.html',
      "best-outdoorsy-spot": 'Dale Ball Trails',
      "bos-link": 'https: //sfct.org/dale-ball-trails/',
      "best-local-fast-food-spot": 'The Burrito Company',
      "blffs-link": 'https: //www.burritocompanysf.com'
    },
    {
      id: '62',
      state: 'New Mexico',
      city: 'Taos',
      "best-cheap-beer-spot": 'Taos Mesa Brewing',
      "bcbs-link": 'https: //www.taosmesabrewing.com',
      "best-dog-friendly-spot": 'Fred Baca Park',
      "bdfs-link": 'https: //www.taosgov.com',
      "best-outdoorsy-spot": 'Carson National Forest',
      "bos-link": 'https: //www.fs.usda.gov/recarea/carson/recreation/ohv/recarea/?recid=44096&actid=29',
      "best-local-fast-food-spot": 'Taos Chicharron Burrito',
      "blffs-link": '1328 Paseo Del Pueblo Sur, Taos, NM 87571'
    },
    {
      id: '63',
      state: 'New York',
      city: 'Rochester',
      "best-cheap-beer-spot": 'Three Heads Brewing',
      "bcbs-link": 'https: //threeheadsbrewing.com',
      "best-dog-friendly-spot": 'Ellison Dog Park',
      "bdfs-link": 'https: //www.monroecounty.gov/parks-DogParks',
      "best-outdoorsy-spot": 'Ontario Beach Park',
      "bos-link": 'https: //www.monroecounty.gov/parks-ontariobeach',
      "best-local-fast-food-spot": 'Yaad Style Jamaican Restaurant',
      "blffs-link": 'https: //yaad-style-jamaican-restaurant.business.site'
    },
    {
      id: '64',
      state: 'New York',
      city: 'Albany',
      "best-cheap-beer-spot": 'Madison Pour House',
      "bcbs-link": 'https: //www.themadisonpourhouse.com',
      "best-dog-friendly-spot": 'Normanskill Farm Dog Park',
      "bdfs-link": 'Mill Rd, Albany, NY 12209',
      "best-outdoorsy-spot": 'Albany Pine Bush',
      "bos-link": 'https: //www.albanypinebush.org',
      "best-local-fast-food-spot": 'Pepper Jacks',
      "blffs-link": 'https: //www.pepperjacksalbany.com/Home'
    },
    {
      id: '65',
      state: 'North Carolina',
      city: 'Raleigh',
      "best-cheap-beer-spot": 'State of Beer',
      "bcbs-link": 'https: //www.stateof.beer',
      "best-dog-friendly-spot": 'Oakwood Dog Park',
      "bdfs-link": 'https: //raleighnc.gov/places/oakwood-park',
      "best-outdoorsy-spot": 'William B. Umstead State Park',
      "bos-link": 'https: //www.ncparks.gov/william-b-umstead-state-park/home',
      "best-local-fast-food-spot": 'Cook Out',
      "blffs-link": 'https: //cookout.com'
    },
    {
      id: '66',
      state: 'North Carolina',
      city: 'Asheville',
      "best-cheap-beer-spot": 'Wicked Weed Brewing',
      "bcbs-link": 'https: //www.wickedweedbrewing.com',
      "best-dog-friendly-spot": 'Carrier Park',
      "bdfs-link": 'https: //www.ashevillenc.gov/department/parks-recreation/',
      "best-outdoorsy-spot": 'Botanical Gardens at Asheville',
      "bos-link": 'https: //ashevillebotanicalgardens.org',
      "best-local-fast-food-spot": 'Bojangles',
      "blffs-link": 'https: //locations.bojangles.com/nc/asheville/99-merrimon-ave.html'
    },
    {
      id: '67',
      state: 'North Dakota',
      city: 'Fargo',
      "best-cheap-beer-spot": 'Fargo Brewing Company',
      "bcbs-link": 'https: //www.fargobrewing.com',
      "best-dog-friendly-spot": 'Brandt Crossing Dog Park and Recreational Area',
      "bdfs-link": '5009 33rd Ave S, Fargo, ND 58104',
      "best-outdoorsy-spot": 'Lindenwood Park',
      "bos-link": 'https: //www.fargoparks.com',
      "best-local-fast-food-spot": 'Burger Time',
      "blffs-link": 'https: //builtbyberg.website'
    },
    {
      id: '68',
      state: 'North Dakota',
      city: 'Bismarck',
      "best-cheap-beer-spot": 'Bismarck Brewing',
      "bcbs-link": 'https: //bismarckbrew.com',
      "best-dog-friendly-spot": 'Kiwanis Park',
      "bdfs-link": 'https: //www.bisparks.org/parks-trails/park-trail-maps/',
      "best-outdoorsy-spot": 'Keelboat Park',
      "bos-link": 'https: //www.bisparks.org/keelboat-park/',
      "best-local-fast-food-spot": 'Big Boy Restaurant',
      "blffs-link": 'https: //bismarckbigboy.com'
    },
    {
      id: '69',
      state: 'Ohio',
      city: 'Cleveland',
      "best-cheap-beer-spot": 'Masthead Brewing Co.',
      "bcbs-link": 'https: //mastheadbrewingco.com',
      "best-dog-friendly-spot": 'Edgewater Park',
      "bdfs-link": 'https: //www.clevelandmetroparks.com/parks/visit/parks/lakefront-reservation/edgewater-park',
      "best-outdoorsy-spot": 'Rocky River Reservation',
      "bos-link": 'https: //www.clevelandmetroparks.com/parks/visit/parks/rocky-river-reservation',
      "best-local-fast-food-spot": 'Hot Dog Diner & Burger Co.',
      "blffs-link": 'http: //www.hotdogdiner.com'
    },
    {
      id: '70',
      state: 'Ohio',
      city: 'Cincinnati',
      "best-cheap-beer-spot": 'MadTree Brewing',
      "bcbs-link": 'https: //www.madtreebrewing.com',
      "best-dog-friendly-spot": 'Otto Armleder Dog Park',
      "bdfs-link": 'https: //www.cincinnatiparks.com',
      "best-outdoorsy-spot": 'Eden Park',
      "bos-link": 'https: //www.cincinnatiparks.com/central/eden-park/',
      "best-local-fast-food-spot": 'Richies Fast Food Restaurant',
      "blffs-link": 'https: //www.richieschicken.com'
    },
    {
      id: '71',
      state: 'Oklahoma',
      city: 'Oklahoma City',
      "best-cheap-beer-spot": 'Stonecloud Brewing',
      "bcbs-link": 'https: //stonecloudbrewing.com',
      "best-dog-friendly-spot": 'Edmond Dog Park at Bickham-Rudkin Park',
      "bdfs-link": 'https: //edmondok.com/Facilities/Facility/Details/3',
      "best-outdoorsy-spot": 'Myriad Botanical Gardens',
      "bos-link": 'https: //oklahomacitybotanicalgardens.com',
      "best-local-fast-food-spot": 'Tuckers Onion Burgers',
      "blffs-link": 'https: //tuckersonionburgers.com'
    },
    {
      id: '72',
      state: 'Oklahoma',
      city: 'Tulsa',
      "best-cheap-beer-spot": 'Valkyrie',
      "bcbs-link": 'https: //valkyrietulsa.com',
      "best-dog-friendly-spot": 'Biscuit Acres Dog Park',
      "bdfs-link": 'https: //biscuitacres.com',
      "best-outdoorsy-spot": 'Gatering Place',
      "bos-link": 'https: //www.gatheringplace.org',
      "best-local-fast-food-spot": 'Hanks Hamburgers',
      "blffs-link": 'https: //m.facebook.com/hankshamburgerstulsa/'
    },
    {
      id: '73',
      state: 'Oregon',
      city: 'Portland',
      "best-cheap-beer-spot": 'Beer',
      "bcbs-link": '1410 SE Stark St, Portland, OR 97214',
      "best-dog-friendly-spot": 'Mt. Tabor Dog Park',
      "bdfs-link": 'https: //www.portlandoregon.gov/parks/39523',
      "best-outdoorsy-spot": 'International Rose Test Garden',
      "bos-link": 'https: //www.portland.gov/parks/washington-park-international-rose-test-garden',
      "best-local-fast-food-spot": 'SuperDeluxe',
      "blffs-link": 'https: //www.eatsuperdeluxe.com'
    },
    {
      id: '74',
      state: 'Oregon',
      city: 'Bend',
      "best-cheap-beer-spot": 'Deschutes Brewery Bend Public House',
      "bcbs-link": 'https: //www.deschutesbrewery.com/visit-us/bend-public-house/',
      "best-dog-friendly-spot": 'GoodDog!',
      "bdfs-link": 'https: //www.fs.usda.gov/main/deschutes/home',
      "best-outdoorsy-spot": 'Shevlin Park',
      "bos-link": 'https: //www.bendparksandrec.org/park/shevlin-park/',
      "best-local-fast-food-spot": 'Dandys Drive-In',
      "blffs-link": 'https: //www.dandysdrivein.com'
    },
    {
      id: '75',
      state: 'Pennsylvania',
      city: 'Philadelphia',
      "best-cheap-beer-spot": 'Dirty Franks',
      "bcbs-link": '347 S 13th St, Philadelphia, PA 19107',
      "best-dog-friendly-spot": 'Penns Landing Dog Park',
      "bdfs-link": '1 N Delaware Ave, Philadelphia, PA 19106',
      "best-outdoorsy-spot": 'Spruce Street Harbor Park',
      "bos-link": 'https: //www.delawareriverwaterfront.com/places/spruce-street-harbor-park',
      "best-local-fast-food-spot": 'Love and Honey Fried Chicken',
      "blffs-link": 'https: //www.loveandhoneyfriedchicken.com'
    },
    {
      id: '76',
      state: 'Pennsylvania',
      city: 'Pittsburgh',
      "best-cheap-beer-spot": 'Brewskis',
      "bcbs-link": 'http: //brewskis.edan.io',
      "best-dog-friendly-spot": 'Frick Park',
      "bdfs-link": 'https: //pittsburghparks.org/explore-your-parks/regional-parks/frick-park/',
      "best-outdoorsy-spot": 'Schenley Park',
      "bos-link": 'https: //pittsburghparks.org/explore-your-parks/regional-parks/schenley-park/',
      "best-local-fast-food-spot": 'Brighton Hot Dog Shoppe',
      "blffs-link": 'https: //brightonhotdogshoppes.com'
    },
    {
      id: '77',
      state: 'Rhode Island',
      city: 'Providence',
      "best-cheap-beer-spot": 'The Malted Brewery',
      "bcbs-link": 'https: //www.themaltedbarley.com/location/the-malted-barley-providence-ri/',
      "best-dog-friendly-spot": 'Dexter Training Ground',
      "bdfs-link": 'Parade St & Willow St, Providence, RI 02909',
      "best-outdoorsy-spot": 'India Point Park',
      "bos-link": 'https: //www.providenceri.gov/departments/',
      "best-local-fast-food-spot": 'Olneyville New York System Restaurant',
      "blffs-link": 'https: //www.olneyvillenewyorksystem.com'
    },
    {
      id: '78',
      state: 'Rhode Island',
      city: 'Newport',
      "best-cheap-beer-spot": 'Pour Judgement',
      "bcbs-link": 'https: //www.pourjudgementnewport.com',
      "best-dog-friendly-spot": 'Newport Dog Park',
      "bdfs-link": '111 JT Connell Hwy, Newport, RI 02840',
      "best-outdoorsy-spot": 'Eastons Beach',
      "bos-link": 'https: //www.cityofnewport.com/en-us/visiting-newport/eastons-beach',
      "best-local-fast-food-spot": 'Mission',
      "blffs-link": 'https: //www.missionnpt.com'
    },
    {
      id: '79',
      state: 'South Carolina',
      city: 'Columbia',
      "best-cheap-beer-spot": 'The Whig',
      "bcbs-link": 'https: //thewhig.org',
      "best-dog-friendly-spot": 'Emily Douglas Park',
      "bdfs-link": 'https: //www.columbiasc.net',
      "best-outdoorsy-spot": 'Columbia Canal and Riverfront Park',
      "bos-link": '312 Laurel St, Columbia, SC 29201',
      "best-local-fast-food-spot": 'Rushs',
      "blffs-link": 'https: //www.rushs.com'
    },
    {
      id: '80',
      state: 'South Carolina',
      city: 'Myrtle Beach',
      "best-cheap-beer-spot": 'The Bowery',
      "bcbs-link": 'https: //thebowery.com',
      "best-dog-friendly-spot": 'Barc Parc South',
      "bdfs-link": '700 Mallard Lake Dr, Myrtle Beach, SC 29577',
      "best-outdoorsy-spot": 'Myrtle Beach State Park',
      "bos-link": 'https: //southcarolinaparks.com/myrtle-beach',
      "best-local-fast-food-spot": 'Burkys Grill',
      "blffs-link": 'https: //www.burkysgrill.com'
    },
    {
      id: '81',
      state: 'South Dakota',
      city: 'Rapid City',
      "best-cheap-beer-spot": 'Lost Cabin Beer Co.',
      "bcbs-link": 'https: //lostcabin.beer',
      "best-dog-friendly-spot": 'Braeburn Dog Park and Ice Rink',
      "bdfs-link": '3324 Idlehurst Ln, Rapid City, SD 57702',
      "best-outdoorsy-spot": 'The Outdoor Campus-West',
      "bos-link": 'https: //gfp.sd.gov/education/',
      "best-local-fast-food-spot": 'Sickies Garage Burgers & Brews',
      "blffs-link": 'http: //sickiesburgers.com'
    },
    {
      id: '82',
      state: 'South Dakota',
      city: 'Sioux Falls',
      "best-cheap-beer-spot": 'Tommy Jacks Bar',
      "bcbs-link": 'https: //www.tommyjacks605.com',
      "best-dog-friendly-spot": 'Spencer Park',
      "bdfs-link": 'https: //www.siouxfalls.org/parks/parks/locations/spencer',
      "best-outdoorsy-spot": 'Falls Park',
      "bos-link": 'https: //www.siouxfalls.org/parks/parks/locations/falls-park',
      "best-local-fast-food-spot": 'Gillbertos',
      "blffs-link": 'https: //www.gilibertos1.com/#/'
    },
    {
      id: '83',
      state: 'Tennessee',
      city: 'Nashville',
      "best-cheap-beer-spot": 'Tennessee Brew Works',
      "bcbs-link": 'https: //www.tnbrew.com',
      "best-dog-friendly-spot": 'Centennial Dog Park',
      "bdfs-link": 'https: //www.nashville.gov/Parks-and-Recreation/Parks/Dog-Parks.aspx',
      "best-outdoorsy-spot": 'Percy Warner Park',
      "bos-link": 'https: //www.nashville.gov/Parks-and-Recreation/Parks/Warner-Parks.aspx',
      "best-local-fast-food-spot": 'Fat Mos',
      "blffs-link": '2620 8th Ave S, Nashville, TN 37204'
    },
    {
      id: '84',
      state: 'Tennessee',
      city: 'Memphis',
      "best-cheap-beer-spot": 'The Absinthe Room',
      "bcbs-link": 'http: //the-absinthe-room.edan.io',
      "best-dog-friendly-spot": 'Shelby Farms Dog Park',
      "bdfs-link": 'https: //www.shelbyfarmspark.org/for-dogs',
      "best-outdoorsy-spot": 'Nesbit Park - Stanky Creek Trails',
      "bos-link": 'https: //www.cityofbartlett.org/65/Parks-Recreation',
      "best-local-fast-food-spot": 'Dyers Burgers',
      "blffs-link": 'http: //www.dyersonbeale.com'
    },
    {
      id: '85',
      state: 'Texas',
      city: 'Austin',
      "best-cheap-beer-spot": 'Draught House Pub & Brewery',
      "bcbs-link": 'https: //www.draughthouse.com',
      "best-dog-friendly-spot": 'Red Bud Isle',
      "bdfs-link": 'https: //austinparks.org/red-bud-isle/',
      "best-outdoorsy-spot": 'Zilker Park and Lady Bird Lake',
      "bos-link": 'https: //austintexas.gov/department/zilker-metropolitan-park',
      "best-local-fast-food-spot": 'P-Terrys',
      "blffs-link": 'https: //pterrys.com'
    },
    {
      id: '86',
      state: 'Texas',
      city: 'Dallas',
      "best-cheap-beer-spot": 'Lee Harveys',
      "bcbs-link": 'http: //leeharveys.com',
      "best-dog-friendly-spot": 'NorthBark Dog Park',
      "bdfs-link": 'http: //www.dallasparks.org/Facilities/Facility/Details/NorthBark-Dog-Park-359',
      "best-outdoorsy-spot": 'The Dallas Arboretum and Botanical Garden',
      "bos-link": 'https: //www.dallasarboretum.org',
      "best-local-fast-food-spot": 'Super Chix',
      "blffs-link": 'https: //www.superchix.com'
    },
    {
      id: '87',
      state: 'Utah',
      city: 'Salt Lake City',
      "best-cheap-beer-spot": 'Beerhive Pub',
      "bcbs-link": 'https: //www.facebook.com/Beerhive-Pub-163241570361229/',
      "best-dog-friendly-spot": 'Herman Franks Dog Park',
      "bdfs-link": 'https: //www.slc.gov/parks/',
      "best-outdoorsy-spot": 'Ensign Trailhead',
      "bos-link": 'https: //utah.com/hiking/ensign-peak',
      "best-local-fast-food-spot": 'Crown Burgers',
      "blffs-link": 'http: //www.crown-burgers.com/locations.php'
    },
    {
      id: '88',
      state: 'Utah',
      city: 'Moab',
      "best-cheap-beer-spot": 'The Blu Pig',
      "bcbs-link": 'http: //www.blupigbbq.com',
      "best-dog-friendly-spot": 'Bark Park',
      "bdfs-link": 'https: //moabcity.org/161/Parks',
      "best-outdoorsy-spot": 'Arches National Park',
      "bos-link": 'https: //www.nps.gov/arch/index.htm',
      "best-local-fast-food-spot": 'Milts Stop and Eat',
      "blffs-link": 'https: //miltsstopandeat.com'
    },
    {
      id: '89',
      state: 'Vermont',
      city: 'Burlington',
      "best-cheap-beer-spot": 'Foam Brewers',
      "bcbs-link": 'https: //www.foambrewers.com',
      "best-dog-friendly-spot": 'Starr Farm Dog Park',
      "bdfs-link": 'https: //enjoyburlington.com/place/starr-farm-park/',
      "best-outdoorsy-spot": 'Oakledge Park',
      "bos-link": '11 Flynn Ave, Burlington, VT 05401',
      "best-local-fast-food-spot": 'Beansies Bus',
      "blffs-link": 'https: //beansies.com'
    },
    {
      id: '90',
      state: 'Vermont',
      city: 'Woodstock',
      "best-cheap-beer-spot": 'Woodstock Hops n Barley',
      "bcbs-link": 'https: //woodstockhopsnbarley.com',
      "best-dog-friendly-spot": 'Watson Upper Valley Dog Park',
      "bdfs-link": 'http: //www.uvdp.org',
      "best-outdoorsy-spot": 'Marsh-Billings-Rockefeller National Historical Park',
      "bos-link": 'https: //www.nps.gov/mabi/index.htm',
      "best-local-fast-food-spot": 'The White Cottage Snack Bar',
      "blffs-link": 'http: //whitecottagesnackbar.com'
    },
    {
      id: '91',
      state: 'Virginia',
      city: 'Virginia Beach',
      "best-cheap-beer-spot": 'The Casual Pint',
      "bcbs-link": 'https: //virginiabeach.thecasualpint.com',
      "best-dog-friendly-spot": 'Red Wing Park',
      "bdfs-link": 'https: //www.vbgov.com/government/departments/parks-recreation/parks-trails/city-parks/pages/red-wing-park.aspx',
      "best-outdoorsy-spot": 'First Landing State Park',
      "bos-link": 'https: //www.dcr.virginia.gov/state-parks/first-landing',
      "best-local-fast-food-spot": 'Aloha Snacks',
      "blffs-link": 'https: //alohasnacksvb.com'
    },
    {
      id: '92',
      state: 'Virginia',
      city: 'Norfolk',
      "best-cheap-beer-spot": 'Brick Anchor Brew House',
      "bcbs-link": 'http: //www.brickanchor.com',
      "best-dog-friendly-spot": 'Lafayette Dog Park',
      "bdfs-link": 'https: //www.norfolk.gov/834/Dog-Parks',
      "best-outdoorsy-spot": 'Norfolk Botanical Garden',
      "bos-link": 'https: //norfolkbotanicalgarden.org',
      "best-local-fast-food-spot": 'Mannys Burger',
      "blffs-link": '2912 Lafayette Blvd, Norfolk, VA 23509'
    },
    {
      id: '93',
      state: 'Washington',
      city: 'Seattle',
      "best-cheap-beer-spot": 'The Pike Brewing Company',
      "bcbs-link": 'https: //www.pikebrewing.com',
      "best-dog-friendly-spot": 'Warren G. Magnuson Park Off Leash Area',
      "bdfs-link": 'http: //www.seattle.gov/parks/find/dog-off-leash-areas?id=398',
      "best-outdoorsy-spot": 'Gas Works Park',
      "bos-link": 'http: //www.seattle.gov/parks/find/parks/gas-works-park',
      "best-local-fast-food-spot": 'Dicks Drive-In',
      "blffs-link": 'https: //www.ddir.com'
    },
    {
      id: '94',
      state: 'Washington',
      city: 'Bellevue',
      "best-cheap-beer-spot": 'Tavern Hall',
      "bcbs-link": 'https: //www.tavern-hall.com',
      "best-dog-friendly-spot": 'Marymoor Off-Leash Dog Park',
      "bdfs-link": 'https: //www.kingcounty.gov/services/parks-recreation/parks/parks-and-natural-lands/popular-parks/marymoor/offleash.aspx',
      "best-outdoorsy-spot": 'Lake Sammamish State Park',
      "bos-link": 'https: //parks.state.wa.us/533/Lake-Sammamish',
      "best-local-fast-food-spot": 'Burgermaster',
      "blffs-link": 'https: //burgermaster.biz'
    },
    {
      id: '95',
      state: 'West Virginia',
      city: 'Charleston',
      "best-cheap-beer-spot": 'Holy City Brewing',
      "bcbs-link": 'https: //holycitybrewing.com',
      "best-dog-friendly-spot": 'Little Creek Park',
      "bdfs-link": '1 Little Creek Park Rd, South Charleston, WV 25309',
      "best-outdoorsy-spot": 'Coonskin Park',
      "bos-link": 'http: //www.kcprc.com/Parks/Coonskin-Park.aspx',
      "best-local-fast-food-spot": 'Black Sheep',
      "blffs-link": 'https: //blacksheepwv.com'
    },
    {
      id: '96',
      state: 'West Virginia',
      city: 'Morgantown',
      "best-cheap-beer-spot": 'Chestnut Brew Works',
      "bcbs-link": 'https: //www.chestnutbrewworksstore.com',
      "best-dog-friendly-spot": 'Krepps Dog Park',
      "bdfs-link": 'http: //www.boparc.org',
      "best-outdoorsy-spot": 'Dorsey Knob Park',
      "bos-link": 'http: //www.boparc.org/dorseys-knob-park.html',
      "best-local-fast-food-spot": 'Tudors Biscuit World',
      "blffs-link": 'http: //www.tudorsbiscuitworld.com'
    },
    {
      id: '97',
      state: 'Wisconsin',
      city: 'Madison',
      "best-cheap-beer-spot": 'The Great Dane Pub and Brewing Company',
      "bcbs-link": 'https: //www.greatdanepub.com',
      "best-dog-friendly-spot": 'Capital Springs Dog Exercise Area',
      "bdfs-link": 'https: //parks-lwrd.countyofdane.com/park/CapitalSpringsRecreationArea',
      "best-outdoorsy-spot": 'Vilas Park',
      "bos-link": 'https: //www.cityofmadison.com/parks/find-a-park/park.cfm?id=1365',
      "best-local-fast-food-spot": 'Natys Fast Food',
      "blffs-link": '1616 Beld St, Madison, WI 53715'
    },
    {
      id: '98',
      state: 'Wisconsin',
      city: 'Green Bay',
      "best-cheap-beer-spot": 'Titletown Brewing Company',
      "bcbs-link": 'https: //www.titletownbrewing.com',
      "best-dog-friendly-spot": 'Howard Dog Park',
      "bdfs-link": 'http: //www.villageofhoward.com/CivicAlerts.aspx?AID=9&ARC=34',
      "best-outdoorsy-spot": 'Wequiock Falls',
      "bos-link": 'https: //www.browncountywi.gov/community/parks-department/general-information/',
      "best-local-fast-food-spot": 'Cousins Subs',
      "blffs-link": 'https: //www.cousinssubs.com/store/cousins-subs-green-bay-w-mason-st-packerland-dr'
    },
    {
      id: '99',
      state: 'Wyoming',
      city: 'Cheyenne',
      "best-cheap-beer-spot": 'Danielmarks Brewing Company Inc',
      "bcbs-link": 'https: //www.danielmarksbrewing.com',
      "best-dog-friendly-spot": 'Lions Park',
      "bdfs-link": 'https: //www.cheyennecity.org/Home',
      "best-outdoorsy-spot": 'Curt Gowdy State Park',
      "bos-link": 'https: //wyoparks.wyo.gov/index.php/places-to-go/curt-gowdy',
      "best-local-fast-food-spot": 'Capitol Cuisine',
      "blffs-link": 'https: //www.facebook.com/capitolcuisine/'
    },
    {
      id: '100',
      state: 'Wyoming',
      city: 'Laramie',
      "best-cheap-beer-spot": 'Altitude Chophouse & Brewery',
      "bcbs-link": 'https: //www.altitudechophouse.com',
      "best-dog-friendly-spot": 'Undine Park',
      "bdfs-link": 'https: //cityoflaramie.org',
      "best-outdoorsy-spot": 'Medicine Bow-Routt National Forest',
      "bos-link": 'https: //www.fs.usda.gov/attmain/mbr/specialplaces',
      "best-local-fast-food-spot": 'Almanzas',
      "blffs-link": '2615 Grand Ave, Laramie, WY 82070'
    },
  ],
};

  

